name: Group Project Workflow
on: push

jobs:
  build:
    name: WorldNapierbuild
    runs-on: ubuntu-20.04
    steps:
      - name: Build JDK
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn compile
      - name: Build Docker Image
        run: docker build -t world-napier .
      - name: Run image
        run: docker run --name napier-container -d world-napier
      - name: view logs
        run: docker logs napier-container
